name: Copy Secrets with Workflows

on:
  workflow_dispatch:
    inputs:
      source-keyvault-name:
        description: 'Source Azure Key Vault Name'
        required: true
      destination-keyvault-name:
        description: 'Destination Azure Key Vault Name'
        required: true

jobs:
  copy-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Check for reruns
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Workflow manually triggered. Checking rerun attempt."
            if [ "$GITHUB_RUN_ATTEMPT" -gt 1 ]; then
              echo "No re-runs for you. Go away."
              exit 1
            else
              echo "Not a re-run. Proceeding with the workflow."
            fi
          fi

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEV_AZURE_CREDENTIALS }}

      - name: Copy secrets from source to destination key vault
        uses: azure/CLI@v1
        with:
          inlineScript: |
            secrets=$(az keyvault secret list --vault-name ${{ github.event.inputs.source-keyvault-name }} --query "[].name" -o tsv)
            for secret in $secrets; do
              value=$(az keyvault secret show --vault-name ${{ github.event.inputs.source-keyvault-name }} --name $secret --query value -o tsv)
              
              # Echo statements without displaying secret values
              echo "Copying secret $secret from ${{ github.event.inputs.source-keyvault-name }} to ${{ github.event.inputs.destination-keyvault-name }}..."
              
              az keyvault secret set --vault-name ${{ github.event.inputs.destination-keyvault-name }} --name $secret --value $value > /dev/null 2>&1
              
              # Wait for the operation to complete
              while [ "$(az keyvault secret show --vault-name ${{ github.event.inputs.destination-keyvault-name }} --name $secret --query 'attributes.enabled' -o tsv)" != "true" ]; do
                echo "Waiting for secret $secret to be enabled in ${{ github.event.inputs.destination-keyvault-name }}..."
                sleep 5
              done
              
              # Additional echo statement to indicate completion
              echo "Secret $secret successfully copied to ${{ github.event.inputs.destination-keyvault-name }}."
            done
        env:
          SOURCE_KV: ${{ github.event.inputs.source-keyvault-name }}
          DEST_KV: ${{ github.event.inputs.destination-keyvault-name }}

      - name: Logout from Azure
        run: |
          az logout

      
