name: creating-secrets-with-whitelisting

on:
  workflow_dispatch:
    inputs:
      keyvault-name:
        description: 'Azure Key Vault Name'
        required: true
      secret-name:
        description: 'Secret Name in Key Vault'
        required: true
      secret-value:
        description: 'Secret Value to be stored in Key Vault'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Whitelist GitHub Runner IP in Key Vault
        id: whitelist
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            set -eu
            agentIP=$(curl -s https://api.ipify.org/)
            echo "GitHub Runner IP: $agentIP"
            az keyvault network-rule add --ip-address $agentIP --name source-keyvault-5
            echo "Network rule added"
            sleep 5

      - name: Create or Update Secret in Azure Key Vault
        id: create-secret
        run: |
          az keyvault secret set --vault-name ${{ github.event.inputs.keyvault-name }} --name ${{ github.event.inputs.secret-name }} --value ${{ github.event.inputs.secret-value }}
          echo "::set-output name=secret-version::$(az keyvault secret show --vault-name ${{ github.event.inputs.keyvault-name }} --name ${{ github.event.inputs.secret-name }} --query 'version' --output tsv)"

      - name: Logout from Azure
        run: |
          az logout
