name: creating secrets but not displaying

on:
  workflow_dispatch:
    inputs:
      keyvault-name:
        description: 'Azure Key Vault Name'
        required: true
      secret-names:
        description: 'Secret Names in Key Vault (comma or colon separated)'
        required: true
      secret-value:
        description: 'Secret Value to be stored in Key Vault'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create or Update Secrets in Azure Key Vault
        id: create-secrets
        run: |
          # Parse secret names from input
          IFS=",:" read -ra secret_names <<< "${{ github.event.inputs.secret-names }}"

          # Loop through each secret name and set/update in Azure Key Vault
          for secret_name in "${secret_names[@]}"; do
            az keyvault secret set --vault-name ${{ github.event.inputs.keyvault-name }} --name "$secret_name" --value "${{ github.event.inputs.secret-value }}"
          done

          echo "Secrets created or updated successfully"

      - name: Get Secrets from Azure Key Vault
        id: get-secrets
        run: |
          # Loop through each secret name and set it in GitHub environment
          for secret_name in "${secret_names[@]}"; do
            echo "${secret_name}_VALUE=$(az keyvault secret show --vault-name ${{ github.event.inputs.keyvault-name }} --name "$secret_name" --query 'value' --output tsv)" >> $GITHUB_ENV
          done

      - name: Use Secrets
        run: |
          # Access the secrets in subsequent steps
          for secret_name in "${secret_names[@]}"; do
            secret_value=$(echo "${secret_name}_VALUE")
            echo "The secret value for $secret_name is $secret_value"
          done


