name: creating multiple secrets and vaules atonce

on:
  workflow_dispatch:
    inputs:
      keyvault-name:
        description: 'Azure Key Vault Name'
        required: true
      secrets:
        description: 'Secrets and Values (comma or colon separated)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create or Update Secrets in Azure Key Vault
        id: create-secrets
        run: |
          # Parse secrets input to get list of secret names and values
          IFS=",:" read -ra secrets <<< "${{ github.event.inputs.secrets }}"

          # Loop through each secret and set/update in Azure Key Vault
          for ((i = 0; i < ${#secrets[@]}; i += 2)); do
            secret_name=${secrets[i]}
            secret_value=${secrets[i + 1]}
            
            # Set or update the secret in Azure Key Vault
            az keyvault secret set --vault-name ${{ github.event.inputs.keyvault-name }} --name "$secret_name" --value "$secret_value"
          done

          echo "Secrets created or updated successfully"

      - name: Get Secrets from Azure Key Vault
        id: get-secrets
        run: |
          # Loop through each secret and set it in GitHub environment
          for ((i = 0; i < ${#secrets[@]}; i += 2)); do
            secret_name=${secrets[i]}
            secret_value=${secrets[i + 1]}

            # Set it in GitHub environment
            echo "${secret_name}_VALUE=$secret_value" >> $GITHUB_ENV
          done

      - name: Use Secrets
        run: |
          # Access the secrets in subsequent steps
          for ((i = 0; i < ${#secrets[@]}; i += 2)); do
            secret_name=${secrets[i]}
            secret_value=${secrets[i + 1]}
            echo "The secret value for $secret_name is $secret_value"
          done
