name: Copy Secrets Workflow

on:
  push:
    branches:
      - main

jobs:
  copy-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Copy secrets from source to destination key vault
        uses: azure/CLI@v1
        with:
          inlineScript: |
            secrets=$(az keyvault secret list --vault-name $SOURCE_KV --query "[].name" -o tsv)
            for secret in $secrets; do
              value=$(az keyvault secret show --vault-name $SOURCE_KV --name $secret --query value -o tsv)
              
              # Echo statements without displaying secret values
              echo "Copying secret $secret from $SOURCE_KV to $DEST_KV..."
              
              az keyvault secret set --vault-name $DEST_KV --name $secret --value $value
              
              # Wait for the operation to complete
              while [ "$(az keyvault secret show --vault-name $DEST_KV --name $secret --query 'attributes.enabled')" != "true" ]; do
                echo "Waiting for secret $secret to be enabled in $DEST_KV..."
                sleep 5
              done
              
              # Additional echo statement to indicate completion
              echo "Secret $secret successfully copied to $DEST_KV."
            done
        env:
          SOURCE_KV: source-keyvault-5
          DEST_KV: destination-keyvault-5

