name: Whitelist GitHub Runner IP

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  whitelist-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Whitelist GitHub Runner IP in Key Vault
        run: |
          set -eu
          agentIP=$(curl -s https://api.ipify.org/)
          echo "GitHub Runner IP: $agentIP"
          az keyvault network-rule add --ip-address $agentIP --vault-name source-keyvault-5
          echo "Network rule added"
          sleep 60
        env:
          AZURE_KEYVAULT_NAME: source-keyvault-5

